spring:
  profiles:
    active: @activatedProperties@
  datasource:
    url: jdbc:postgresql://localhost:5432/agreement
    username: postgres
    password: Bharath11
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
  security:
    oauth2:
      clientId : 1000.7QO888PL2DNBUTWTF4ZYBTFYCP8WTT
      clientSecret : 9fb7ef11fc906f9c70fe20fb2bfabc3802beed3d09
      refreshToken : 1000.9c66eedccb90f3144c7a310cc2ca0170.5dbf0228df8886f1771744e0dc81a615
      client:
        registration:
          facebook:
            client-id: 3595831953830598
            client-secret: 1677bd5512e65068e789f5545aca8179
          google:
            client-id: 808574382755-mncrrbn87qa7sqvrd1smuqd062u4796a.apps.googleusercontent.com
            client-secret: beKWHyaEOtOIHfBXi5ip2i1V
  mail:
    port: 587
    host: smtp.zoho.eu
    username: rentpal@zohomail.eu
    password: Bharath11
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 2
          multiplier: 1.5
          max-interval: 5000

angular: http://localhost:4200

app:
  settings:
    rabbitmq:
      queue: notification_queue
      exchange: notification_exchange
      routingKey: notification

server:
  port: 8082
  tomcat:
    use-relative-redirects: true
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
  forward-headers-strategy: framework

zoho:
  accounts:
    oauth: https://accounts.zoho.eu/oauth/v2/token
  sign:
    requests: https://sign.zoho.eu/api/v1/requests
    template: https://sign.zoho.eu/api/v1/templates/16312000000011003/createdocument
