spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/agreement
    username: postgres
    password: Bharath11
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true

angular: http://localhost:4200

